// Generates TypeScript types from /templates/schemas/*.schema.json (P8: the
// schema is the single source of truth; these types are derived, never edited).
// Deterministic: same schemas in -> same files out. Run: npm run gen
import { compileFromFile } from "json-schema-to-typescript";
import { readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = join(here, "..", "..", "templates", "schemas");
const outDir = join(here, "..", "src", "types", "generated");

// facts-file.schema.json is a Phase-1 contract; the renderer never reads facts.
const SKIP = new Set(["facts-file.schema.json"]);

const BANNER =
  "/* GENERATED by render/scripts/generate-types.mjs from /templates/schemas — DO NOT EDIT. */\n";

mkdirSync(outDir, { recursive: true });

const files = readdirSync(schemasDir)
  .filter((f) => f.endsWith(".schema.json") && !SKIP.has(f))
  .sort();

const indexLines = [BANNER];
for (const file of files) {
  const base = file.replace(/\.schema\.json$/, "");
  const ts = await compileFromFile(join(schemasDir, file), {
    bannerComment: BANNER,
    cwd: schemasDir,
    additionalProperties: false,
    style: { singleQuote: false },
  });
  writeFileSync(join(outDir, `${base}.ts`), ts);
  indexLines.push(`export * from "./${base}";`);
  console.log(`generated ${base}.ts`);
}
writeFileSync(join(outDir, "index.ts"), indexLines.join("\n") + "\n");
console.log(`generated index.ts (${files.length} schemas)`);
